@token=Bearer

###
POST https://fgp.one/api/auth/create
Content-Type: application/json
Authorization: {{token}}

{
  "name": "User",
  "email": "demo@gmail.com",
  "username": "fgp555",
  "password": "P4s5W0rD@123",
  "role": "admin"
}

###
POST https://fgp.one/api/auth/login
Content-Type: application/json

{
  "username": "user123",
  "password": "securepassword123"
}

###
GET https://fgp.one/api/auth/findAll
Authorization: {{token}}

###
GET https://fgp.one/api/auth/findOne/241130234111
Authorization: {{token}}

###
GET https://fgp.one/api/auth/search?query=2411
Authorization: {{token}}

###
PUT https://fgp.one/api/auth/update/241130234111
Content-Type: application/json
Authorization: {{token}}

{
  "email": "update@example.com",
  "username": "user123",
  "password": "securepassword123",
  "role": "user"
}

###
DELETE https://fgp.one/api/auth/remove/241130234111
Authorization: {{token}}

###
DELETE https://fgp.one/api/auth/deleteMany
Authorization: {{token}}

###
GET https://fgp.one/api/auth/findOneEmail/user@example.com
Authorization: {{token}}



### ==========        ==========
### ========== backup ==========
### ==========        ==========

### POST https://fgp.one/api/auth/backup_restore_upload
### GET https://fgp.one/api/auth/download/backup-1-shorts-241130230827.json

###
POST https://fgp.one/api/auth/backup_create
Authorization: {{token}}

###
POST https://fgp.one/api/auth/backup_list
Authorization: {{token}}

###
POST https://fgp.one/api/auth/backup_restore/backup-1-shorts-241130230827.json
Authorization: {{token}}

###
DELETE https://fgp.one/api/auth/backup_delete/backup-1-shorts-241130230827.json
Authorization: {{token}}

