@token=Bearer

# GET http://localhost:3000/api/note/backup


###
POST http://localhost:3000/api/note
Content-Type: application/json

{
  "_id": "231129000000",
  "title": "Primera Nota",
  "content": "<meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Document</title>"
}

###
POST http://localhost:3000/api/note
Content-Type: application/json

{
  "title": "Primera Nota",
  "content": "const startServer = async () => {\n  try {\n    await connectMongoDB();\n    server.listen(3000, () => {\n      console.log(`listening on http://localhost:3000/`);\n    });\n  } catch (error) {\n    console.error(\"Error starting the server:\", error);\n  }\n};"
}


###
GET http://localhost:3000/api/note
Content-Type: application/json

###
GET http://localhost:3000/api/note/search/2411
Content-Type: application/json

###
GET http://localhost:3000/api/note/241201101045
Content-Type: application/json

###
PUT http://localhost:3000/api/note/241201101045
Content-Type: application/json
Authorization: {{token}}

{
  "title": "Nota Actualizada",
  "content": "Este es el contenido actualizado de la nota."
}

###
DELETE http://localhost:3000/api/note/241201101045
Content-Type: application/json
Authorization: {{token}}

###
DELETE http://localhost:3000/api/note/delete-all
Content-Type: application/json
Authorization: {{token}}



### ========== backups ==========
### POST http://localhost:3000/api/note/restore/multer

###
GET http://localhost:3000/api/note/backup
Authorization: {{token}}

###
POST http://localhost:3000/api/note/restore/backup-notes-241201095935.json
Authorization: {{token}}

###
GET http://localhost:3000/api/note/backups-list
Authorization: {{token}}

###
DELETE http://localhost:3000/api/note/backup/backup-notes-241201095935.json
Authorization: {{token}}

