@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiIyNDEyMDEwMTE1NDAiLCJ1c2VybmFtZSI6InVzZXIxMjMiLCJyb2xlIjoidXNlciIsImVtYWlsIjoidXNlckBleGFtcGxlLmNvbSIsImlhdCI6MTczNzUzMTU5NiwiZXhwIjoxNzM4Mzk1NTk2fQ.QTvD2lglVMpYS19ZR3fxEAa8fRmTHvpLqt2si43Toyw

# GET http://localhost:3000/api/note/backup


###
POST http://localhost:3000/api/note
Content-Type: application/json

{
  "_id": "231129000001",
  "title": "Primera Nota",
  "content": "<meta charset=\"UTF-8\">\n    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\n    <title>Document</title>"
}

###
POST http://localhost:3000/api/note
Content-Type: application/json

{
  "title": "Primera Nota",
  "content": "const startServer = async () => {\n  try {\n    await connectMongoDB();\n    server.listen(3000, () => {\n      console.log(`listening on http://localhost:3000/`);\n    });\n  } catch (error) {\n    console.error(\"Error starting the server:\", error);\n  }\n};"
}


###
GET http://localhost:3000/api/note
Content-Type: application/json

###
GET http://localhost:3000/api/note/search/2411
Content-Type: application/json

###
GET http://localhost:3000/api/note/250122073909
Content-Type: application/json

###
PUT http://localhost:3000/api/note/250122073909
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "title": "Nota Actualizada",
  "content": "Este es el contenido actualizado de la nota. aaa"
}

###
DELETE http://localhost:3000/api/note/250122073909
Content-Type: application/json
Authorization: Bearer {{token}}

###
DELETE http://localhost:3000/api/note/delete-all
Content-Type: application/json
Authorization: Bearer {{token}}



### ========== backups ==========
### POST http://localhost:3000/api/note/restore/multer

###
GET http://localhost:3000/api/note/backup
Authorization: Bearer {{token}}

###
GET http://localhost:3000/api/note/backups-list
Authorization: Bearer {{token}}

###
POST http://localhost:3000/api/note/restore/backup-notes-250122123528.json
Authorization: Bearer {{token}}

###
DELETE http://localhost:3000/api/note/backup/backup-notes-250122123528.json
Authorization: Bearer {{token}}

