### 1. Create a Shortened URL
POST http://localhost:3000/api/shortener/shorten
Content-Type: application/json

{
  "originalUrl": "https://www.example.com",
  "shortUrl": "mi-acortada2"
}

### 
GET http://localhost:3000/api/shortener/

### 2. Access the Original URL via Shortened URL
# GET http://localhost:3000/api/shortener/mi-acortada1

### 3. Get the Statistics for a Shortened URL
GET http://localhost:3000/api/shortener/stats/mi-acortada1



### 5. Test with a Non-Existent Shortened URL (404)
GET http://localhost:3000/api/shortener/shortened-does-not-exist
