
POST http://localhost:3000/create
Content-Type: application/json

{
  "originalUrl": "https://www.example.com",
  "shortUrl": "exampleTemp"
}

###
GET http://localhost:3000/findAll

###
GET http://localhost:3000/findOne/241130172949


###
PUT http://localhost:3000/update/241130172949
Content-Type: application/json

{
  "originalUrl": "https://www.example.com",
  "shortUrl": "exampleTemp2"
}

###
DELETE http://localhost:3000/remove/241130172949
Content-Type: application/json


### ==========        ==========
### ========== backup ==========
### ==========        ==========

### POST http://localhost:3000/backup_restore_upload
### GET http://localhost:3000/download/backup-all.json

###
POST http://localhost:3000/backup_create

###
POST http://localhost:3000/backup_list

###
POST http://localhost:3000/backup_restore/backup-all.json

###
DELETE http://localhost:3000/backup_delete/backup-all.json



# ========== shortener ==========
### GET http://localhost:3000/exampleTemp?param1=value1
### GET http://localhost:3000/shortened-does-not-exist
DELETE http://localhost:3000/deleteMany

###
POST http://localhost:3000/reset_visit_count

###
GET http://localhost:3000/findOneShortUrl/exampleTemp

###
GET http://localhost:3000/search/2411
