// https://chat.openai.com/c/ca7ed684-014c-4b13-8921-6b6f5e3d2312

// data.js

const preguntas = [
  {
    id: 1,
    pregunta: "¿Cuál es el resultado de la siguiente expresión en JavaScript: '2 + 3 * 4'?",
    opciones: ["20", "14", "15", "16"],
    respuestaCorrecta: "14",
  },
  {
    id: 2,
    pregunta: "¿Cuál es el valor de '5 == \"5\"' en JavaScript?",
    opciones: ["true", "false", "NaN", "undefined"],
    respuestaCorrecta: "true",
  },
  {
    id: 3,
    pregunta: "¿Qué método se utiliza en JavaScript para agregar un elemento al final de un array?",
    opciones: [".pop()", ".shift()", ".push()", ".unshift()"],
    respuestaCorrecta: ".push()",
  },
  {
    id: 4,
    pregunta: "¿Cuál es el resultado de '5 === \"5\"' en JavaScript?",
    opciones: ["true", "false", "NaN", "undefined"],
    respuestaCorrecta: "false",
  },
  {
    id: 5,
    pregunta: "¿Cuál es el operador de asignación en JavaScript?",
    opciones: ["=", "==", "===", "!="],
    respuestaCorrecta: "=",
  },
  {
    id: 6,
    pregunta: "¿Qué hace el método 'parseInt(\"10.5\")' en JavaScript?",
    opciones: ["Devuelve 10", "Devuelve 11", "Devuelve 10.5", "Devuelve NaN"],
    respuestaCorrecta: "Devuelve 10",
  },
  {
    id: 7,
    pregunta: "¿Qué hace el método 'toFixed()' en JavaScript?",
    opciones: [
      "Devuelve un número redondeado al entero más cercano",
      "Devuelve un número redondeado hacia abajo",
      "Devuelve un número redondeado hacia arriba",
      "Devuelve un número con un número fijo de decimales",
    ],
    respuestaCorrecta: "Devuelve un número con un número fijo de decimales",
  },
  {
    id: 8,
    pregunta: '¿Cuál es el resultado de \'"Hola" + " Mundo"\' en JavaScript?',
    opciones: ["Hola Mundo", "HolaMundo", "Hola + Mundo", "NaN"],
    respuestaCorrecta: "Hola Mundo",
  },
  {
    id: 9,
    pregunta: "¿Cuál es la función en JavaScript para imprimir mensajes en la consola?",
    opciones: ["print()", "log()", "console.log()", "write()"],
    respuestaCorrecta: "console.log()",
  },
  {
    id: 10,
    pregunta: "¿Qué palabra clave se utiliza para declarar una variable en JavaScript?",
    opciones: ["var", "int", "string", "let"],
    respuestaCorrecta: "var",
  },
  {
    id: 11,
    pregunta: "¿Cuál es la forma correcta de comentar en JavaScript?",
    opciones: ["// Comentario", "<!-- Comentario -->", "/* Comentario */", "# Comentario"],
    respuestaCorrecta: "// Comentario",
  },
  {
    id: 12,
    pregunta: "¿Cuál es el resultado de 5 + '5' en JavaScript?",
    opciones: ["10", "55", "25", "Error"],
    respuestaCorrecta: "55",
  },
  {
    id: 13,
    pregunta: "¿Cuál es la forma correcta de acceder al primer elemento de un array en JavaScript?",
    opciones: ["array[1]", "array.first", "array[0]", "array.first()"],
    respuestaCorrecta: "array[0]",
  },
  {
    id: 14,
    pregunta: "¿Qué hace el método 'toUpperCase()' en JavaScript?",
    opciones: ["Convierte una cadena a minúsculas", "Convierte una cadena a mayúsculas", "Devuelve la longitud de una cadena", "Elimina espacios en blanco de una cadena"],
    respuestaCorrecta: "Convierte una cadena a mayúsculas",
  },
  {
    id: 15,
    pregunta: "¿Qué significa 'NaN' en JavaScript?",
    opciones: ["No es un número", "Nuevo Array Numérico", "Número Aleatorio Negativo", "Ninguna de las anteriores"],
    respuestaCorrecta: "No es un número",
  },
  {
    id: 16,
    pregunta: "¿Cuál es el operador de concatenación de cadenas en JavaScript?",
    opciones: ["&", "+", "*", "/"],
    respuestaCorrecta: "+",
  },
  {
    id: 17,
    pregunta: "¿Cuál es el resultado de 'typeof []' en JavaScript?",
    opciones: ["array", "object", "string", "number"],
    respuestaCorrecta: "object",
  },
  {
    id: 18,
    pregunta: "¿Qué método se utiliza para eliminar el último elemento de un array en JavaScript?",
    opciones: [".delete()", ".remove()", ".pop()", ".slice()"],
    respuestaCorrecta: ".pop()",
  },
  {
    id: 19,
    pregunta: "¿Cuál es la forma correcta de representar un comentario de múltiples líneas en JavaScript?",
    opciones: ["// Comentario", "<!-- Comentario -->", "/* Comentario */", "# Comentario"],
    respuestaCorrecta: "/* Comentario */",
  },
  {
    id: 20,
    pregunta: "¿Cuál es la función utilizada para obtener la longitud de un array en JavaScript?",
    opciones: ["length()", "size()", "count()", "length"],
    respuestaCorrecta: "length",
  },
  {
    id: 21,
    pregunta: "¿Qué método se utiliza para convertir una cadena en un array en JavaScript?",
    opciones: [".split()", ".concat()", ".join()", ".slice()"],
    respuestaCorrecta: ".split()",
  },
  {
    id: 22,
    pregunta: "¿Cuál es la forma correcta de comparar dos valores en JavaScript para verificar si son iguales en valor y tipo?",
    opciones: ["===", "==", "=", "!="],
    respuestaCorrecta: "===",
  },
  {
    id: 23,
    pregunta: "¿Qué tipo de bucle se utiliza para iterar sobre un objeto en JavaScript?",
    opciones: ["for", "while", "do...while", "for...in"],
    respuestaCorrecta: "for...in",
  },
  {
    id: 24,
    pregunta: "¿Cuál es el operador lógico 'Y' en JavaScript?",
    opciones: ["&&", "||", "!", "&"],
    respuestaCorrecta: "&&",
  },
  {
    id: 25,
    pregunta: "¿Qué método se utiliza para agregar o modificar elementos en un array en JavaScript?",
    opciones: [".push()", ".pop()", ".shift()", ".splice()"],
    respuestaCorrecta: ".splice()",
  },
  {
    id: 26,
    pregunta: "¿Qué hace el método 'toString()' en JavaScript?",
    opciones: [
      "Convierte un número a una cadena",
      "Convierte una cadena a un número",
      "Devuelve la representación de cadena de un objeto",
      "Devuelve la representación de objeto de una cadena",
    ],
    respuestaCorrecta: "Devuelve la representación de cadena de un objeto",
  },
  {
    id: 27,
    pregunta: "¿Cuál es la palabra clave utilizada para declarar una función en JavaScript?",
    opciones: ["method", "function", "func", "declare"],
    respuestaCorrecta: "function",
  },
  {
    id: 28,
    pregunta: "¿Qué método se utiliza para ordenar un array en JavaScript?",
    opciones: [".sort()", ".order()", ".arrange()", ".organize()"],
    respuestaCorrecta: ".sort()",
  },
  {
    id: 29,
    pregunta: "¿Cuál es el resultado de 'typeof undefined' en JavaScript?",
    opciones: ["undefined", "null", "object", "string"],
    respuestaCorrecta: "undefined",
  },
  {
    id: 30,
    pregunta: "¿Cuál es la salida de 'console.log(typeof null)' en JavaScript?",
    opciones: ["null", "undefined", "object", "number"],
    respuestaCorrecta: "object",
  },
  {
    id: 31,
    pregunta: "¿Qué evento se dispara cuando el usuario hace clic en un elemento HTML?",
    opciones: ["onmouseover", "onkeydown", "onclick", "onchange"],
    respuestaCorrecta: "onclick",
  },
  {
    id: 32,
    pregunta: "¿Qué hace el método 'substring()' en JavaScript?",
    opciones: [
      "Devuelve una subcadena a partir de un índice especificado",
      "Reemplaza una subcadena por otra",
      "Elimina espacios en blanco de una cadena",
      "Convierte una cadena a mayúsculas",
    ],
    respuestaCorrecta: "Devuelve una subcadena a partir de un índice especificado",
  },
  {
    id: 33,
    pregunta: "¿Cuál es la forma correcta de declarar un objeto en JavaScript?",
    opciones: ["{ }", "( )", "[ ]", "< >"],
    respuestaCorrecta: "{ }",
  },
  {
    id: 34,
    pregunta: "¿Qué método se utiliza para convertir una cadena a minúsculas en JavaScript?",
    opciones: [".toLowerCase()", ".toUpperCase()", ".trim()", ".slice()"],
    respuestaCorrecta: ".toLowerCase()",
  },
  {
    id: 35,
    pregunta: "¿Qué hace el método 'Math.random()' en JavaScript?",
    opciones: [
      "Devuelve un número aleatorio entre 0 (inclusive) y 1 (exclusivo)",
      "Devuelve un número aleatorio entre 0 y 100",
      "Devuelve un número entero aleatorio",
      "Devuelve un número aleatorio negativo",
    ],
    respuestaCorrecta: "Devuelve un número aleatorio entre 0 (inclusive) y 1 (exclusivo)",
  },
  {
    id: 36,
    pregunta: "¿Cuál es la forma correcta de incluir comentarios en una línea de código en JavaScript?",
    opciones: ["// Comentario", "<!-- Comentario -->", "/* Comentario */", "# Comentario"],
    respuestaCorrecta: "// Comentario",
  },
  {
    id: 37,
    pregunta: "¿Qué operador se utiliza para concatenar cadenas en JavaScript?",
    opciones: ["+", "-", "*", "/"],
    respuestaCorrecta: "+",
  },
  {
    id: 38,
    pregunta: "¿Cuál es el resultado de '5 > 3 && 2 < 4' en JavaScript?",
    opciones: ["true", "false", "NaN", "undefined"],
    respuestaCorrecta: "true",
  },
  {
    id: 39,
    pregunta: "¿Qué método se utiliza para eliminar un elemento específico de un array en JavaScript?",
    opciones: [".delete()", ".remove()", ".splice()", ".pop()"],
    respuestaCorrecta: ".splice()",
  },
  {
    id: 40,
    pregunta: "¿Qué palabra clave se utiliza para declarar una constante en JavaScript?",
    opciones: ["const", "let", "var", "final"],
    respuestaCorrecta: "const",
  },
  {
    id: 41,
    pregunta: "¿Cuál es la forma correcta de incluir comentarios de múltiples líneas en JavaScript?",
    opciones: ["// Comentario", "<!-- Comentario -->", "/* Comentario */", "# Comentario"],
    respuestaCorrecta: "/* Comentario */",
  },
  {
    id: 42,
    pregunta: "¿Qué función se utiliza para convertir una cadena en un entero en JavaScript?",
    opciones: ["parseInt()", "parseFloat()", "toInteger()", "toNumber()"],
    respuestaCorrecta: "parseInt()",
  },
  {
    id: 43,
    pregunta: "¿Cuál es el operador de negación en JavaScript?",
    opciones: ["!", "-", "*", "/"],
    respuestaCorrecta: "!",
  },
  {
    id: 44,
    pregunta: "¿Qué método se utiliza para obtener la hora actual en JavaScript?",
    opciones: ["getHour()", "currentHour()", "getHours()", "currentTime()"],
    respuestaCorrecta: "getHours()",
  },
  {
    id: 45,
    pregunta: "¿Qué método se utiliza para dividir una cadena en un array en JavaScript?",
    opciones: [".split()", ".concat()", ".join()", ".slice()"],
    respuestaCorrecta: ".split()",
  },
  {
    id: 46,
    pregunta: "¿Cuál es el resultado de 'null == undefined' en JavaScript?",
    opciones: ["true", "false", "NaN", "undefined"],
    respuestaCorrecta: "true",
  },
  {
    id: 47,
    pregunta: "¿Qué método se utiliza para redondear un número a la cantidad de decimales especificada en JavaScript?",
    opciones: [".toFixed()", ".round()", ".floor()", ".ceil()"],
    respuestaCorrecta: ".toFixed()",
  },
  {
    id: 48,
    pregunta: "¿Cuál es la forma correcta de declarar una función de flecha en JavaScript?",
    opciones: ["function() {}", "() => {}", "=> {}", "(params) => {}"],
    respuestaCorrecta: "() => {}",
  },
  {
    id: 49,
    pregunta: "¿Cuál es el resultado de '2 + '2'' en JavaScript?",
    opciones: ["4", "22", "Error", "NaN"],
    respuestaCorrecta: "22",
  },
  {
    id: 50,
    pregunta: "¿Cuál es el resultado de 'typeof function() {}' en JavaScript?",
    opciones: ["function", "object", "undefined", "string"],
    respuestaCorrecta: "function",
  },
];

module.exports = preguntas;
